Update TESTE_WORKFLOW.yml

diff --git a/.github/workflows/TESTE_WORKFLOW.yml b/.github/workflows/TESTE_WORKFLOW.yml
--- a/.github/workflows/TESTE_WORKFLOW.yml
+++ b/.github/workflows/TESTE_WORKFLOW.yml
@@ -19,11 +19,29 @@ jobs:
             echo "IS_BUG=true" >> $GITHUB_ENV
           fi
 
+#      - name: Obter project-id pelo número do projeto
+#        if: env.IS_BUG == 'true'
+#        run: |
+#          PROJECT_ID=$(gh project list --owner Leo-Fernandes-sh3 --format json \
+#            | jq -r '.projects[] | select(.number == 5) | .id')
+#          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
+#        env:
+#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Obter project-id pelo número do projeto
         if: env.IS_BUG == 'true'
         run: |
+          echo "🔎 Buscando project-id..."
           PROJECT_ID=$(gh project list --owner Leo-Fernandes-sh3 --format json \
             | jq -r '.projects[] | select(.number == 5) | .id')
+
+          echo "::notice::PROJECT_ID=$PROJECT_ID"
+
+          if [ -z "$PROJECT_ID" ]; then
+            echo "::error::PROJECT_ID não encontrado"
+            exit 1
+          fi
+
           echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
